import { Num } from "../numbers";

export const SI_PREFIXES_LONG: { [prefix: string]: Num } = {
    "quecto": { type: "rational", n: 1n, d: 10n ** 30n },
    "ronto": { type: "rational", n: 1n, d: 10n ** 27n },
    "yocto": { type: "rational", n: 1n, d: 10n ** 24n },
    "zepto": { type: "rational", n: 1n, d: 10n ** 21n },
    "atto": { type: "rational", n: 1n, d: 10n ** 18n },
    "femto": { type: "rational", n: 1n, d: 10n ** 15n },
    "pico": { type: "rational", n: 1n, d: 10n ** 12n },
    "nano": { type: "rational", n: 1n, d: 1_000_000_000n },
    "micro": { type: "rational", n: 1n, d: 1_000_000n },
    "milli": { type: "rational", n: 1n, d: 1000n },
    "centi": { type: "rational", n: 1n, d: 100n },
    "deci": { type: "rational", n: 1n, d: 10n },
    "deca": { type: "int", int: 10n },
    "hecto": { type: "int", int: 100n },
    "kilo": { type: "int", int: 1000n },
    "mega": { type: "int", int: 1_000_000n },
    "giga": { type: "int", int: 1_000_000_000n },
    "tera": { type: "int", int: 10n ** 12n },
    "peta": { type: "int", int: 10n ** 15n },
    "exa": { type: "int", int: 10n ** 18n },
    "zetta": { type: "int", int: 10n ** 21n },
    "yotta": { type: "int", int: 10n ** 24n },
    "ronna": { type: "int", int: 10n ** 27n },
    "quetta": { type: "int", int: 10n ** 30n },
};

export const SI_PREFIXES_SHORT: { [prefix: string]: Num } = {
    "q": { type: "rational", n: 1n, d: 10n ** 30n },
    "r": { type: "rational", n: 1n, d: 10n ** 27n },
    "y": { type: "rational", n: 1n, d: 10n ** 24n },
    "z": { type: "rational", n: 1n, d: 10n ** 21n },
    "a": { type: "rational", n: 1n, d: 10n ** 18n },
    "f": { type: "rational", n: 1n, d: 10n ** 15n },
    "p": { type: "rational", n: 1n, d: 10n ** 12n },
    "n": { type: "rational", n: 1n, d: 1_000_000_000n },
    "\xb5": { type: "rational", n: 1n, d: 1_000_000n },
    "mc": { type: "rational", n: 1n, d: 1_000_000n },
    "m": { type: "rational", n: 1n, d: 1000n },
    "c": { type: "rational", n: 1n, d: 100n },
    "d": { type: "rational", n: 1n, d: 10n },
    "da": { type: "int", int: 10n },
    "h": { type: "int", int: 100n },
    "k": { type: "int", int: 1000n },
    "M": { type: "int", int: 1_000_000n },
    "G": { type: "int", int: 1_000_000_000n },
    "T": { type: "int", int: 10n ** 12n },
    "P": { type: "int", int: 10n ** 15n },
    "E": { type: "int", int: 10n ** 18n },
    "Z": { type: "int", int: 10n ** 21n },
    "Y": { type: "int", int: 10n ** 24n },
    "R": { type: "int", int: 10n ** 27n },
    "Q": { type: "int", int: 10n ** 30n },
};

export const BINARY_PREFIXES_LONG: { [prefix: string]: Num } = {
    "kibi": { type: "int", int: 1024n },
    "mebi": { type: "int", int: 1024n ** 2n },
    "gibi": { type: "int", int: 1024n ** 3n },
    "tebi": { type: "int", int: 1024n ** 4n },
    "pebi": { type: "int", int: 1024n ** 5n },
    "exbi": { type: "int", int: 1024n ** 6n },
    "zebi": { type: "int", int: 1024n ** 7n },
    "yobi": { type: "int", int: 1024n ** 8n },
    "robi": { type: "int", int: 1024n ** 9n },
    "quebi": { type: "int", int: 1024n ** 10n },
};

export const BINARY_PREFIXES_SHORT: { [prefix: string]: Num } = {
    "Ki": { type: "int", int: 1024n },
    "Mi": { type: "int", int: 1024n ** 2n },
    "Gi": { type: "int", int: 1024n ** 3n },
    "Ti": { type: "int", int: 1024n ** 4n },
    "Pi": { type: "int", int: 1024n ** 5n },
    "Ei": { type: "int", int: 1024n ** 6n },
    "Zi": { type: "int", int: 1024n ** 7n },
    "Yi": { type: "int", int: 1024n ** 8n },
    "Ri": { type: "int", int: 1024n ** 9n },
    "Qi": { type: "int", int: 1024n ** 10n },
};